name: Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      BASE_URL:  ${{ secrets.BASE_URL }}
      ESTAT_APPID:  ${{ secrets.ESTAT_APPID }}

    steps:
      - uses: actions/checkout@v2

      # 「./dist」にビルド結果が生成する
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run generate

      # Netlifyにデプロイする
      - run: npx netlify-cli deploy --dir=dist  --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
