name: Netlify_Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      # 「./dist」にビルド結果が生成する
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run generate

      # Netlifyにデプロイする
      - run: npx netlify-cli deploy --dir=dist  --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEVELOP_ID: ${{ secrets.NETLIFY_DEVELOP_ID }}
